### ISSUE TITLE
Waiting for region...

### ISSUE THREAD

**Issue by ruizlenato** [Tadly/hideIt.sh#10]
➜  ~ ./hideIt.sh --name '^Polybar tray window$' --region 1366x768+0+0
Searching window...
Found window with id: 18874379
Fetching window dimensions...
Fetching screen dimensions...
Initially hiding window...
Defined region:
  X: 1366 1366
  Y: 768 768

Waiting for region...

**Comment by tadly** [comment]
Fix what exactly?
Given the output, everything is working as intended.

If your issue is that the region is to small, you have to actually make it bigger like so:
```
--region 1366x768+10+10
```
This would give you a 10px by 10px area

**Comment by ruizlenato** [comment]
I put the mouse on top where it was supposed to appear and nothing happens

**Comment by tadly** [comment]
With such little information I can't really help you much.

Does the window initially hide when you run the command?
What is your screen resolution?
Did you set `override-redirect = true` in your polybar config?

**Comment by ruizlenato** [comment]
![image](https://user-images.githubusercontent.com/49354525/78065598-e6d99180-7369-11ea-881f-6ad88b85cb46.png)

**Comment by tadly** [comment]
okay and what about my other questions?
You gotta work with me man or I can't help you

**Comment by ruizlenato** [comment]
Minha resolução é 1366x768

**Comment by tadly** [comment]
Dificuldades de linguagem. Entendo.
Estou usando o google tradutor para escrever isso agora.

O seu polybar se oculta quando você inicia o script?

**Comment by ruizlenato** [comment]
(English) Yes, the polybar is hidden

(Portuguese) Sim, a polybar fica oculta

**Comment by tadly** [comment]
OK. Suponho que você tenha polybar no canto inferior esquerdo?

Sua região seria acionada no canto inferior direito (não à esquerda)
Tente o seguinte:
```
hideIt.sh --name '^Polybar tray window$' --region 0x768+10+-40
```

**Comment by ruizlenato** [comment]
eu usei o

>  xdotool getmouselocation

e funcionou para eu ver a localização, muito obrigado isso pode ajudar o próximo também :3
