### ISSUE TITLE
Hiding and unhiding rapidly when cursor is not over it

### ISSUE THREAD

**Issue by mushi-nova** [Tadly/hideIt.sh#12]
Recently I downloaded the script and currently I'm running it to hide the system tray in the polybar. Though it is hiding the system tray perfectly it is glitching when I move the cursor over it and it starts to hide and unhide itself rapidly. It continues to happen when the cursor is not over it. I'm using the following command to hide it
`hideIt.sh --name '^Polybar tray window$' -H -p 5 -d left -i 0.5 & disown`

Don't know if I'm doing something wrong in here or if it is just a bug that is causing the glitch.

**Comment by tadly** [comment]
This is explained in the FAQ section in the readme :)
