### ISSUE TITLE
Not hiding polybar

### ISSUE THREAD

**Issue by dkibet** [Tadly/hideIt.sh#4]
I ran `hideIt.sh -N "polybar-top_eDP1" -p 3 -d top -H -i 0.3` but it didn't hide main polybar

**Comment by tadly** [comment]
For this to work you have to have `override-redirect = true` set for your that bar

**Comment by dkibet** [comment]
> For this to work you have to have `override-redirect = true` set for your that bar

I already have that in my config.

**Comment by tadly** [comment]
What DE/WM are you using?
Also, please add the config for your top bar.

**Comment by tadly** [comment]
And while you're at it, add the output of `hideIt.sh -N "polybar-top_eDP1" -p 3 -d top -H -i 0.3`

**Comment by dkibet** [comment]
> What DE/WM are you using?
> Also, please add the config for your top bar.

Sorry forgot to give you details 
I'm using i3 on arch linux 
[My polybar config](https://gist.github.com/dkibet/4aed916271894fe5c84aa801fa49ec10/raw/1d0808139dd94e76d69330c21bdf95bdb46ca17c/polybar%2520config)

Searching window...
Found window with id: 10485761
Fetching window dimensions...
Fetching screen dimensions...
Initially hiding window...
Waiting for HOVER...

that is the output

**Comment by tadly** [comment]
`override-redirect = true` needs to be part of the `[bar/top]` section.

**Comment by dkibet** [comment]
> `override-redirect = true` needs to be part of the `[bar/top]` section.

Thanks! worked.

**Comment by tadly** [comment]
Glad to hear it!
