### ISSUE TITLE
startup polybar not hide (manually run it on terminal working fine)

### ISSUE THREAD

**Issue by thyeun** [Tadly/hideIt.sh#9]
Sorry for asking this, i been include an auto startup in i3 with the below line

`exec_always --no-startup-id hideIt.sh -N '^polybar-mainbar-i3_LVDS1$' -d bottom -s 1 -H &`

but the polybar still wont startup hide.

And i already included `override-redirect = true`.

Manually run it on terminal, it working fine.

**Comment by tadly** [comment]
Most likely this is because the window doesn't exist yet.

Try:
```
exec_always --no-startup-id hideIt.sh -w -N '^polybar-mainbar-i3_LVDS1$' -d bottom -s 1 -H &
```

**Comment by thyeun** [comment]
Thanks it working with the `-w`, i think.

Sorry i noob on this

**Comment by tadly** [comment]
No problem. We all learn :)
Glad it's working now
